//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RpgTurno.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RpgTurno.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ally.
        /// </summary>
        internal static string Ally {
            get {
                return ResourceManager.GetString("Ally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Any.
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ArcherUnit.
        /// </summary>
        internal static string ArcherUnit {
            get {
                return ResourceManager.GetString("ArcherUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ArrowRain.
        /// </summary>
        internal static string ArrowRain {
            get {
                return ResourceManager.GetString("ArrowRain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ArrowRainDescription.
        /// </summary>
        internal static string ArrowRainDescription {
            get {
                return ResourceManager.GetString("ArrowRainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BarracksOfValorStage.
        /// </summary>
        internal static string BarracksOfValorStage {
            get {
                return ResourceManager.GetString("BarracksOfValorStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bless.
        /// </summary>
        internal static string Bless {
            get {
                return ResourceManager.GetString("Bless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a BlessDescription.
        /// </summary>
        internal static string BlessDescription {
            get {
                return ResourceManager.GetString("BlessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a By.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cleared.
        /// </summary>
        internal static string Cleared {
            get {
                return ResourceManager.GetString("Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cleave.
        /// </summary>
        internal static string Cleave {
            get {
                return ResourceManager.GetString("Cleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CleaveDescription.
        /// </summary>
        internal static string CleaveDescription {
            get {
                return ResourceManager.GetString("CleaveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ClericUnit.
        /// </summary>
        internal static string ClericUnit {
            get {
                return ResourceManager.GetString("ClericUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ConfirmSaveDeletion.
        /// </summary>
        internal static string ConfirmSaveDeletion {
            get {
                return ResourceManager.GetString("ConfirmSaveDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Congratulations.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cooldown.
        /// </summary>
        internal static string Cooldown {
            get {
                return ResourceManager.GetString("Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Credits.
        /// </summary>
        internal static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CurrentCooldown.
        /// </summary>
        internal static string CurrentCooldown {
            get {
                return ResourceManager.GetString("CurrentCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Curse.
        /// </summary>
        internal static string Curse {
            get {
                return ResourceManager.GetString("Curse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CurseDescription.
        /// </summary>
        internal static string CurseDescription {
            get {
                return ResourceManager.GetString("CurseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DaysAgo.
        /// </summary>
        internal static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Defeated.
        /// </summary>
        internal static string Defeated {
            get {
                return ResourceManager.GetString("Defeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DefeatedSupremeWarrior.
        /// </summary>
        internal static string DefeatedSupremeWarrior {
            get {
                return ResourceManager.GetString("DefeatedSupremeWarrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Difficulty.
        /// </summary>
        internal static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DivineLight.
        /// </summary>
        internal static string DivineLight {
            get {
                return ResourceManager.GetString("DivineLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DivineLightDescription.
        /// </summary>
        internal static string DivineLightDescription {
            get {
                return ResourceManager.GetString("DivineLightDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DontForgetToLeaveSuggestions.
        /// </summary>
        internal static string DontForgetToLeaveSuggestions {
            get {
                return ResourceManager.GetString("DontForgetToLeaveSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EffectsVolume.
        /// </summary>
        internal static string EffectsVolume {
            get {
                return ResourceManager.GetString("EffectsVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EmptySlot.
        /// </summary>
        internal static string EmptySlot {
            get {
                return ResourceManager.GetString("EmptySlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enemy.
        /// </summary>
        internal static string Enemy {
            get {
                return ResourceManager.GetString("Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EvilArcherUnit.
        /// </summary>
        internal static string EvilArcherUnit {
            get {
                return ResourceManager.GetString("EvilArcherUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EvilClericUnit.
        /// </summary>
        internal static string EvilClericUnit {
            get {
                return ResourceManager.GetString("EvilClericUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EvilLancerUnit.
        /// </summary>
        internal static string EvilLancerUnit {
            get {
                return ResourceManager.GetString("EvilLancerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EvilPawnUnit.
        /// </summary>
        internal static string EvilPawnUnit {
            get {
                return ResourceManager.GetString("EvilPawnUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EvilTowerStage.
        /// </summary>
        internal static string EvilTowerStage {
            get {
                return ResourceManager.GetString("EvilTowerStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EvilWarriorUnit.
        /// </summary>
        internal static string EvilWarriorUnit {
            get {
                return ResourceManager.GetString("EvilWarriorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Execution.
        /// </summary>
        internal static string Execution {
            get {
                return ResourceManager.GetString("Execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ExecutionDescription.
        /// </summary>
        internal static string ExecutionDescription {
            get {
                return ResourceManager.GetString("ExecutionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fortress.
        /// </summary>
        internal static string Fortress {
            get {
                return ResourceManager.GetString("Fortress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FortressDescription.
        /// </summary>
        internal static string FortressDescription {
            get {
                return ResourceManager.GetString("FortressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fullscreen.
        /// </summary>
        internal static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GoingToWave.
        /// </summary>
        internal static string GoingToWave {
            get {
                return ResourceManager.GetString("GoingToWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GuardStance.
        /// </summary>
        internal static string GuardStance {
            get {
                return ResourceManager.GetString("GuardStance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GuardStanceDescription.
        /// </summary>
        internal static string GuardStanceDescription {
            get {
                return ResourceManager.GetString("GuardStanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Heal.
        /// </summary>
        internal static string Heal {
            get {
                return ResourceManager.GetString("Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HealDescription.
        /// </summary>
        internal static string HealDescription {
            get {
                return ResourceManager.GetString("HealDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HeavySlash.
        /// </summary>
        internal static string HeavySlash {
            get {
                return ResourceManager.GetString("HeavySlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HeavySlashDescription.
        /// </summary>
        internal static string HeavySlashDescription {
            get {
                return ResourceManager.GetString("HeavySlashDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ImprovisedStrike.
        /// </summary>
        internal static string ImprovisedStrike {
            get {
                return ResourceManager.GetString("ImprovisedStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ImprovisedStrikeDescription.
        /// </summary>
        internal static string ImprovisedStrikeDescription {
            get {
                return ResourceManager.GetString("ImprovisedStrikeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LancerUnit.
        /// </summary>
        internal static string LancerUnit {
            get {
                return ResourceManager.GetString("LancerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LastBastion.
        /// </summary>
        internal static string LastBastion {
            get {
                return ResourceManager.GetString("LastBastion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LastBastionDescription.
        /// </summary>
        internal static string LastBastionDescription {
            get {
                return ResourceManager.GetString("LastBastionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LastPlay.
        /// </summary>
        internal static string LastPlay {
            get {
                return ResourceManager.GetString("LastPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MainMenu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ManaCost.
        /// </summary>
        internal static string ManaCost {
            get {
                return ResourceManager.GetString("ManaCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MoreContentComingSoon.
        /// </summary>
        internal static string MoreContentComingSoon {
            get {
                return ResourceManager.GetString("MoreContentComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MusicVolume.
        /// </summary>
        internal static string MusicVolume {
            get {
                return ResourceManager.GetString("MusicVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PiercingStrike.
        /// </summary>
        internal static string PiercingStrike {
            get {
                return ResourceManager.GetString("PiercingStrike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PiercingStrikeDescription.
        /// </summary>
        internal static string PiercingStrikeDescription {
            get {
                return ResourceManager.GetString("PiercingStrikeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pike.
        /// </summary>
        internal static string Pike {
            get {
                return ResourceManager.GetString("Pike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PikeDescription.
        /// </summary>
        internal static string PikeDescription {
            get {
                return ResourceManager.GetString("PikeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PoisonShoot.
        /// </summary>
        internal static string PoisonShoot {
            get {
                return ResourceManager.GetString("PoisonShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PoisonShootDescription.
        /// </summary>
        internal static string PoisonShootDescription {
            get {
                return ResourceManager.GetString("PoisonShootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Portuguese.
        /// </summary>
        internal static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PowerShoot.
        /// </summary>
        internal static string PowerShoot {
            get {
                return ResourceManager.GetString("PowerShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PowerShootDescription.
        /// </summary>
        internal static string PowerShootDescription {
            get {
                return ResourceManager.GetString("PowerShootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Progress.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Repair.
        /// </summary>
        internal static string Repair {
            get {
                return ResourceManager.GetString("Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RepairDescription.
        /// </summary>
        internal static string RepairDescription {
            get {
                return ResourceManager.GetString("RepairDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ReturnToMap.
        /// </summary>
        internal static string ReturnToMap {
            get {
                return ResourceManager.GetString("ReturnToMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Self.
        /// </summary>
        internal static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shoot.
        /// </summary>
        internal static string Shoot {
            get {
                return ResourceManager.GetString("Shoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ShootDescription.
        /// </summary>
        internal static string ShootDescription {
            get {
                return ResourceManager.GetString("ShootDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ShowFps.
        /// </summary>
        internal static string ShowFps {
            get {
                return ResourceManager.GetString("ShowFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Single.
        /// </summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Slash.
        /// </summary>
        internal static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SlashDescription.
        /// </summary>
        internal static string SlashDescription {
            get {
                return ResourceManager.GetString("SlashDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Slot.
        /// </summary>
        internal static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Smite.
        /// </summary>
        internal static string Smite {
            get {
                return ResourceManager.GetString("Smite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SmiteDescription.
        /// </summary>
        internal static string SmiteDescription {
            get {
                return ResourceManager.GetString("SmiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Snipe.
        /// </summary>
        internal static string Snipe {
            get {
                return ResourceManager.GetString("Snipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SnipeDescription.
        /// </summary>
        internal static string SnipeDescription {
            get {
                return ResourceManager.GetString("SnipeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SpearSweep.
        /// </summary>
        internal static string SpearSweep {
            get {
                return ResourceManager.GetString("SpearSweep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SpearSweepDescription.
        /// </summary>
        internal static string SpearSweepDescription {
            get {
                return ResourceManager.GetString("SpearSweepDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SupremeWarriorUnit.
        /// </summary>
        internal static string SupremeWarriorUnit {
            get {
                return ResourceManager.GetString("SupremeWarriorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TargetAmount.
        /// </summary>
        internal static string TargetAmount {
            get {
                return ResourceManager.GetString("TargetAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TargetType.
        /// </summary>
        internal static string TargetType {
            get {
                return ResourceManager.GetString("TargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ThanksForPlaying.
        /// </summary>
        internal static string ThanksForPlaying {
            get {
                return ResourceManager.GetString("ThanksForPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TheCastleStage.
        /// </summary>
        internal static string TheCastleStage {
            get {
                return ResourceManager.GetString("TheCastleStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WarriorUnit.
        /// </summary>
        internal static string WarriorUnit {
            get {
                return ResourceManager.GetString("WarriorUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wave.
        /// </summary>
        internal static string Wave {
            get {
                return ResourceManager.GetString("Wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WindowSize.
        /// </summary>
        internal static string WindowSize {
            get {
                return ResourceManager.GetString("WindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
