namespace Domain.Enum.Unit;

public enum UnitCode
{
    Archer = 0,
    Cleric = 1,
    Lancer = 2,
    Warrior = 3,
    EvilArcher = 4,
    EvilCleric = 5,
    EvilLancer = 6,
    EvilWarrior = 7,
    SupremeWarrior = 9,
    Pawn = 10,
    EvilPawn = 11,
    Bear = 12,
    BombFish = 13,
    Gnoll = 14,
    Gnome = 15,
    HarpoonShark = 16,
    HexShaman = 17,
    Lizard = 18,
    Minotaur = 19,
    PaddleShark = 20,
    Panda = 21,
    Turtle = 22,
    PigRider = 23,
    Skull = 24,
    Snake = 25,
    SpearGoblin = 26,
    Spider = 27,
    Thief = 28,
    TorchGoblin = 29,
    Troll = 30,
}
